openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Fetch all users
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      tags:
      - Users
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: User already exists
      tags:
      - Users
  /api/users/{user_id}:
    get:
      summary: Fetch user by ID
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
      tags:
      - Users
  /api/roles:
    get:
      summary: Fetch all roles
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
      tags:
      - Roles
    post:
      summary: Create a role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '201':
          description: Role created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
      tags:
      - Roles
  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
      tags:
      - Authentication
  /api/admin/logs:
    get:
      summary: Fetch system logs
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: {}
      tags:
      - Admin Operations
  /api/system/health:
    get:
      summary: Check API health
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: {}
      tags:
      - System Monitoring
  /api/system/time:
    get:
      summary: Fetch server time
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: date-time
      tags:
      - System Monitoring
  /api/utils/info:
    get:
      summary: Fetch utility info
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: {}
      tags:
      - Utilities
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
          format: email
      required:
      - id
      - name
      - email
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
      - id
      - name
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
      - email
      - password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        token_type:
          type: string
      required:
      - token
      - token_type
